/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import { z } from 'zod';
import * as CommonSchema from '../common_schema.gen';

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator `yarn openapi:generate`.
 */

export const CsvToArray = (value: unknown) => {
  if (typeof value === 'string') {
    return value.split(',');
  }
  return value;
};

export const AnotherField = CommonSchema.SortOrder;
export type AnotherField = z.infer<typeof AnotherField>;
