/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import { z } from 'zod';
import * as CommonSchema from '../../common_schema.gen';

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator `yarn openapi:generate`.
 */

export const ImportRulesRequestQuery = z.object({
  /**
   * Determines whether existing rules with the same `rule_id` are overwritten.
   */
  overwrite: CommonSchema.StringToBooleanDefaultFalse,
  /**
   * Determines whether existing exception lists with the same `list_id` are overwritten.
   */
  overwrite_exceptions: CommonSchema.StringToBooleanDefaultFalse,
  /**
   * Determines whether existing actions with the same `kibana.alert.rule.actions.id` are overwritten.
   */
  overwrite_action_connectors: CommonSchema.StringToBooleanDefaultFalse,
  /**
   * TODO
   */
  as_new_list: CommonSchema.StringToBooleanDefaultFalse,
});
export type ImportRulesRequestQuery = z.infer<typeof ImportRulesRequestQuery>;
export type ImportRulesRequestQueryInput = z.input<typeof ImportRulesRequestQuery>;

export const ImportRulesRequestParams = z.undefined();
export type ImportRulesRequestParams = z.infer<typeof ImportRulesRequestParams>;
export type ImportRulesRequestParamsInput = z.input<typeof ImportRulesRequestParams>;

export const ImportRulesRequestBody = z.undefined();
export type ImportRulesRequestBody = z.infer<typeof ImportRulesRequestBody>;
export type ImportRulesRequestBodyInput = z.input<typeof ImportRulesRequestBody>;

export const ImportRulesResponse = z.object({
  exceptions_success: z.boolean(),
  exceptions_success_count: z.number(),
  exceptions_errors: z.array(CommonSchema.ErrorSchema),
  rules_count: z.number(),
  success: z.boolean(),
  success_count: z.number(),
  errors: z.array(CommonSchema.ErrorSchema),
  action_connectors_errors: z.array(CommonSchema.ErrorSchema),
  action_connectors_warnings: z.array(CommonSchema.WarningSchema),
  action_connectors_success: z.boolean(),
  action_connectors_success_count: z.number(),
});
export type ImportRulesResponse = z.infer<typeof ImportRulesResponse>;
